# Generated by Django 3.0.4 on 2020-11-30 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tidal', '0002_auto_20201129_2355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gridattr',
            name='id',
        ),
        migrations.AlterField(
            model_name='gridattr',
            name='girdNum',
            field=models.BigIntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
