# Generated by Django 3.0.4 on 2020-11-30 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tidal', '0003_auto_20201130_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dategrid',
            name='date',
            field=models.DateField(),
        ),
    ]
