# Generated by Django 3.0.4 on 2020-12-02 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tidal', '0005_auto_20201130_2232'),
    ]

    operations = [
        migrations.CreateModel(
            name='GirdSplice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startCoor', models.CharField(max_length=100)),
                ('endCoor', models.CharField(max_length=100)),
                ('length', models.BigIntegerField(default=0)),
                ('name', models.CharField(max_length=500)),
                ('date', models.DateField()),
            ],
        ),
    ]
